# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: bastion-cli
    main: ./apps/cli
    binary: bastion-cli
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

  - id: bastion-server
    main: ./apps/server
    binary: bastion-server
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - id: bastion-archive
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

sboms:
  - disable: true

dockers_v2:
  - id: bastion-server
    ids: [bastion-server]
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion-server"
      - "dcdavidev/bastion-server"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    dockerfile: docker/server.Dockerfile
    platforms: [linux/amd64, linux/arm64]
    sbom: false
    extra_files:
      - packages/core/db/migrations

  - id: bastion-cli
    ids: [bastion-cli]
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion-cli"
      - "dcdavidev/bastion-cli"
    tags:
      - "latest"
      - "{{ .Tag }}"
    dockerfile: docker/cli.Dockerfile
    platforms: [linux/amd64, linux/arm64]
    sbom: false

nfpms:
  - id: bastion-nfpm
    package_name: bastion-cli
    formats: [deb, rpm, apk]
    vendor: dcdavidev
    homepage: https://github.com/dcdavidev/bastion
    maintainer: Davide Di Criscito <dcdavidev@gmail.com>
    description: Bastion CLI
    license: MIT

snapcrafts:
  - id: bastion-snap
    name: bastion-cli
    summary: Bastion CLI
    description: Bastion is a tool for managing project secrets.
    grade: stable
    confinement: strict
    publish: true
    apps:
      bastion:
        command: bastion-cli
        plugs: [network, home]

brews:
  - name: bastion-cli
    repository:
      owner: dcdavidev
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI"
    license: "MIT"
    install: |
      bin.install "bastion-cli" => "bastion"

scoops:
  - name: bastion-cli
    repository:
      owner: dcdavidev
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI"
    license: "MIT"

aurs:
  - name: bastion-cli-bin
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI"
    maintainers: ["Davide Di Criscito <dcdavidev@gmail.com>"]
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY_FILE }}"
    git_url: "ssh://aur@aur.archlinux.org/bastion-cli-bin.git"

release:
  github:
    owner: dcdavidev
    name: bastion
  extra_files:
    - glob: ./bastion.png
    - glob: ./bastion-banner.png
  replace_existing_artifacts: true

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:"]
