# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need generate
    - go generate ./...

builds:
  - id: bastion
    main: ./cmd/bastion
    binary: bastion
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: bastion-server
    main: ./cmd/server
    binary: bastion-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    # this name template makes the search and replace of the binary name
    # easier in shell scripts.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: dcdavidev
    name: bastion

snapcrafts:
  - id: bastion
    ids:
      - bastion
    name: bastion
    summary: Bastion CLI - Secure secret management and execution
    description: |
      Bastion is a tool for managing project secrets and running commands
      with those secrets injected into the environment securely.
    grade: stable
    confinement: strict
    publish: true
    apps:
      bastion:
        command: bastion
        plugs:
          - network
          - home

dockers:
  - id: bastion-server
    ids:
      - bastion-server
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion-server:latest"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion-server:{{ .Tag }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion-server:v{{ .Major }}"
    dockerfile: docker/server.Dockerfile
    goos: linux
    goarch: amd64
    extra_files:
      - internal/db/migrations
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - id: bastion-cli
    ids:
      - bastion
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion:latest"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion:{{ .Tag }}"
    dockerfile: docker/cli.Dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }} CLI"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

brews:
  - name: bastion
    repository:
      owner: dcdavidev
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI - Secure secret management and execution"
    license: "MIT"
    install: |
      bin.install "bastion"
