# .goreleaser.yaml
# Documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: bastion
    main: ./apps/cli
    binary: bastion
    hooks:
      post:
        - mkdir -p packages/bastion/bin/{{ .Os }}_{{ .Arch }}
        - cp {{ .Path }} packages/bastion/bin/{{ .Os }}_{{ .Arch }}/{{ .Name }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: bastion-server
    main: ./apps/server
    binary: bastion-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: bastion
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: dcdavidev
    name: bastion
  extra_files:
    - glob: ./bastion.png
    - glob: ./bastion-banner.png
  replace_existing_artifacts: true

snapcrafts:
  - id: bastion
    ids:
      - bastion
    name: bastion
    summary: Bastion CLI - Secure secret management and execution
    description: |
      Bastion is a tool for managing project secrets and running commands
      with those secrets injected into the environment securely.
    grade: stable
    confinement: strict
    publish: true
    apps:
      bastion:
        command: bastion
        plugs:
          - network
          - home

dockers_v2:
  - id: bastion-server
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion-server"
      - "dcdavidev/bastion-server"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    dockerfile: docker/server.Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - packages/core/db/migrations
    build_flags:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - id: bastion-cli
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/bastion"
      - "dcdavidev/bastion"
    tags:
      - "latest"
      - "{{ .Tag }}"
    dockerfile: docker/cli.Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    build_flags:
      - "--label=org.opencontainers.image.title={{ .ProjectName }} CLI"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

homebrew_casks:
  - name: bastion
    repository:
      owner: dcdavidev
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI - Secure secret management and execution"
    license: "MIT"
    binaries:
      - bastion

scoops:
  - name: bastion
    repository:
      owner: dcdavidev
      name: scoop-bucket
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI - Secure secret management and execution"
    license: "MIT"

nfpms:
  - id: bastion
    package_name: bastion
    ids:
      - bastion
    vendor: dcdavidev
    homepage: https://github.com/dcdavidev/bastion
    maintainer: Davide Di Criscito <dcdavidev@gmail.com>
    description: Bastion CLI - Secure secret management and execution
    license: MIT
    formats:
      - deb
      - rpm
      - apk

aurs:
  - name: bastion-bin
    ids:
      - bastion
    homepage: "https://github.com/dcdavidev/bastion"
    description: "Bastion CLI - Secure secret management and execution"
    maintainers:
      - "Davide Di Criscito <dcdavidev@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/bastion-bin.git"

chocolateys:
  - name: bastion
    ids:
      - bastion
    owners: dcdavidev
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    description: "Bastion CLI - Secure secret management and execution"
    authors: Davide Di Criscito
    license_url: "https://github.com/dcdavidev/bastion/blob/main/LICENSE"
